name: 'composer-php'
description: 'Runs composer'
inputs:
  action:
    description: 'Runs any composer command in your actions'
    required: false
    default: help
outputs:
  composer-output:
    description: 'The output of the docker command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
branding:
    icon: 'package'
    color: 'green'