#!/bin/sh
composer $* > composer.out
output="$(cat composer.out)"
output="${output//$'\n'/\\n}"
output="${output// / }"     # replace regular space with 'En Space'
echo "composer-output=$output" >> $GITHUB_OUTPUT
echo "composer-cache-dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
